### ISSUE TITLE
Not enough twitch subscriptions

### ISSUE THREAD

**Issue by PokimaneYes** [jamesbt365/nix-config#4]
you should subscribe to more twitch streamers. You can subscribe using twitch prime, you get it for free if you have amazon prime

**Comment by MathewRouse** [comment]
i agree
![CHAV](https://user-images.githubusercontent.com/47611746/151886871-5768b5a7-fc17-4d7f-8bae-9f1b9c6cd3ef.jpg)

**Comment by PokimaneYes** [comment]
> i agree ![CHAV](https://user-images.githubusercontent.com/47611746/151886871-5768b5a7-fc17-4d7f-8bae-9f1b9c6cd3ef.jpg)

beautiful

**Comment by jamesbt365** [comment]
- [ ] add twitch subscriptions?

**Comment by MathewRouse** [comment]
https://user-images.githubusercontent.com/47611746/151886944-9a8a833b-4767-4c69-8b20-35f5778fc313.mp4

**Comment by MathewRouse** [comment]
[2D platformer code.odt](https://github.com/jamesbt365/nix-config/files/7974790/2D.platformer.code.odt)

**Comment by PokimaneYes** [comment]
tiandi more likekeen Eye wasn't given his name for his good eyesight, rather for how excited he gets over carving an opponents eye sockets out. Part dumbass and part warrior, K.E loves nothing more than to sink his blade into a challenging opponent. His broken morale compass is balanced out by his strong sense of respect towards strong warriors. When he does meet a fellow warrior on the battlefield, he hunkers down and takes it seriously. Although K.E seems like a blundering buffoon, he is in fact a calculated warrior who analyses his opponents and uses his overwhelming rage and resilience to defeat them

**Comment by MathewRouse** [comment]
![Tory Drew](https://user-images.githubusercontent.com/47611746/151887089-bcc98fb2-48f8-4e3a-824d-3b3a11c346af.png)

**Comment by MathewRouse** [comment]
> tiandi more likekeen Eye wasn't given his name for his good eyesight, rather for how excited he gets over carving an opponents eye sockets out. Part dumbass and part warrior, K.E loves nothing more than to sink his blade into a challenging opponent. His broken morale compass is balanced out by his strong sense of respect towards strong warriors. When he does meet a fellow warrior on the battlefield, he hunkers down and takes it seriously. Although K.E seems like a blundering buffoon, he is in fact a calculated warrior who analyses his opponents and uses his overwhelming rage and resilience to defeat them

More like Bore Ragnorok

**Comment by MathewRouse** [comment]
![Rare_logo_SoT_themed_COL](https://user-images.githubusercontent.com/47611746/151887172-cf80f011-bd6d-4408-ac19-7a7fa1fb2fd4.png)

**Comment by MathewRouse** [comment]
![Stokes Pog](https://user-images.githubusercontent.com/47611746/151887258-34916785-5754-4e20-b987-180ad2dea52f.jpg)

**Comment by MathewRouse** [comment]
[https://www.twitch.tv/jamesbt365](url)

**Comment by PokimaneYes** [comment]
stokes pog>hog rider

**Comment by jamesbt365** [comment]
I have decided no.
